### ISSUE TITLE
I don't understand the Readme :(

### ISSUE THREAD

**Issue by sadraskol** [thomaslule/fixed-footnotes#1]
It reads to call `fixedFootnotes();`, but i don't understand the prerequisites for that.

If I understood, I need:
- Links that point to a note
- a note with the legend
- call the library and it will work ?

In the end the container for the notes and the float container do not share the same styling, which is quite disturbing.

There's a small gap on the demo, as shown here:
![capture du 2017-03-22 23-46-53](https://cloud.githubusercontent.com/assets/2914331/24224165/f18ea57e-0f59-11e7-924e-dc0831b0081c.png)

**Comment by thomaslule** [comment]
Oh yes I forgot to explain the html part but you understood correctly. I'll add it to README.

I don't see the gap on firefox and chrome

**Comment by sadraskol** [comment]
Can we consider the issue closed? (i think we can)

**Comment by thomaslule** [comment]
yup
