### ISSUE TITLE
Mobile overlap

### ISSUE THREAD

**Issue by sadraskol** [thomaslule/fixed-footnotes#2]
On mobile view (tested in latest Android Chrome), the footnote container is hidden by the fixed notes
![capture du 2017-03-22 23-50-19](https://cloud.githubusercontent.com/assets/2914331/24224235/5c7d1730-0f5a-11e7-933a-4cd2dde08655.png)

**Comment by thomaslule** [comment]
Oh it looks like it doesn't work properly when there are css `@media` queries activated, I'll look into that

**Comment by thomaslule** [comment]
Fixed in v1.1.0
