### ISSUE TITLE
js fail with markdown footnote syntax

### ISSUE THREAD

**Issue by ConstantMath** [thomaslule/fixed-footnotes#6]
Hi,
Thanks for this nice script.
I use footnotes generated from markdown. 
Classicaly markdown footnotes are generated like this : 
`<a href="#fn:1" class="footnote-ref">1</a>`

..but it fails with your script that uses the `querySelector`function because of the colon contained in the link.

`Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#fn:1' is not a valid selector.`

Any idea how to resolve it ?

Many thanks !

**Comment by thomaslule** [comment]
Hey, thanks for your report

I published an update that should solve your problem! Get the v1.1.1 :)

**Comment by ConstantMath** [comment]
Wow, it works.
Thanks a lot Thomas for the quick fix.
All the best.
